info_fields = [
    # Informations demographiques et administratives
    'Date de naissance',
    'Sexe',
    'Poids',
    'Taille',
    'Date d\'admission',
    'Date d\'intervention',
    'Date de sortie',
    
    # Parametres biologiques et etat initial
    'Creat pre op',
    'Clairance de la creat',
    'Dialyse',
    
    # Antecedents et comorbidites
    'Diabete',
    'Traitement diabete pre op',
    'BPCO',
    'EI ttt par ATB',
    'EI sterilisee',
    'Atteinte neuro musculo squelettique',
    'Stenose carotidienne ou intervention',
    'AOMI',
    'Aorte intervention',
    'NYHA',
    'ATCD chirurgie ouverture pericardiaque',
    'Nombre',
    'Type intervention cardiaque ANT',
    'HTA',
    'Hypercholesterolemie',
    'Tabac',
    'FA',
    'Stimulateur cardiaque implante',
    
    # État cardiaque pre operatoire
    'Angor classe IV',
    'IDM<90j',
    'TV ou FV<24h',
    'Choc cardiogenique/anurie/oligurie<24h',
    'Inotropes voie IV',
    'Ballon contre pulsion',
    'ECMO/ECLS',
    'Intubation pre op',
    'Massage cardiaque pre op',
    'FEVG',
    'PAPS',
    
    # Caracteristiques de l'intervention
    'Degre d\'urgence',
    'Complexite de l\'intervention',
    'Chirurgie de l\'aorte',
    'Flap intimal',
    'Maladie des tissus elastiques',
    'CIV post infarctus',
    'NB branche coronaire stenosees',
    'SS TCCG',
    'ATCD ATL/Stent',
    
    # Évaluation valvulaire
    'IA(0/1/2/3/4)',
    'RA',
    'Etiologie valve aortique',
    'IM(0/1/2/3/4)',
    'RM',
    'Etiologie valve mitrale',
    'IT',
    'Etiologie valve tricuspide',
    'IP',
    'RP',
    'Etiologie valve pulmonaire',
    
    # Traitements preoperatoires
    'AVK pre op',
    'NACO pre op',
    'AAG pre op',
    'double AAG',
    
    # Contexte COVID
    'Sars Cov 2 prouve par PCR',
    'COVID 19 symptomatique',
    'Patient recule pour COVID 19',
    
    # Parametres echocardiographiques
    'DTD',
    'DTS',
    'SIV',
    'Paroi posterieure',
    'Chambre de chasse',
    'Cinetique paroi anterieure',
    'Cinetique paroi laterale',
    'Cinetique paroi inferieure',
    'Rupture parietale ou CIV',
    'Epanchement pericardique',
    'VCI',
    'Epaississement pericarde',
    'Thrombus/Tumeur OD',
    'Thrombus/tumeur OG',
    'Aspect',
    
    # Mesures valvulaires et hemodynamiques
    'IA',
    'Gradient max',
    'Gradient moyen',
    'Vmax',
    'Surface effective',
    'Surace indexeee',
    'ITV sous aortique',
    'ITV aortique',
    'Index de permeabillite',
    'SOR',
    'Volume regurgitant',
    'Temps 1/2 pression',
    'Reflux diastolique crosse (OUI/NON)',
    
    # Évaluation mitrale
    'IM',
    'Prolapsus',
    'Rupture de cordage',
    'IM dystrophique (Barlow)',
    'Cordages epaissis/raccourcis',
    'Calcifications',
    'Diametre anneau mitral',
    'OG dilatee',
    'Surface de l\'OG',
    'Volume de l\'OG',
    'Volume indexe de l\'OG',
    'RM : surface effective',
    'RM : gradient moyen',
    
    # Évaluation tricuspide et ventriculaire droite
    'Diametre anneau tricuspide',
    'TAPSE',
    'Strain longitudinal global',
    'S\'',
    'Rapport E/A',
    'Rapport E/E\'',
    'Fonction VD',
    'Flux inverse veines sus hepatiques',
    'Dilatation OD',
    'Dilatation VD',
    'Dilatation VCI',
    
    # Mesures anatomiques
    'Insuffisance pulmonaire',
    'Diametre anneau pulmonaire',
    'Gradient maximal pulmonaire',
    'Gradient moyen pulmonaire',
    'Diametre anneau aortique',
    'Sinus de valsalva',
    'JST',
    'Aorte tubulaire',
    'Diametre tronc artere pulmonaire',
    
    # Details chirurgicaux
    'CEC',
    'Duree de clampage',
    'Duree CEC',
    'Intervention necessitant une protection cerebrale',
    'Type de protection cerebrale',
    'Geste video assiste',
    'Voie d\'abord',
    'Si voie d\'abord endovasculaire',
    'Si voie d\'abord transthoracique',
    'Si voie d\'abord peripherique',
    'Chirurgien 1',
    'Chirurgien 2',
    'Chirurgien en formation',
    'Chirurgien chirurgie structuelle',
    
    # Informations sur la chirurgie
    'Type de chirurgie',
    'NB total de conduit arteriel',
    'NB anastomoses coronaires avec conduit arteriel',
    'NB total conduit veineux',
    'NB anastomoses coronaires avec conduit veineux',
    
    # Informations sur les protheses valvulaires
    'VA_Geste valvulaire',
    'VA_Type de prothese',
    'VA_Fabricant',
    'VA_Modele',
    'VA_Taille (mm)',
    'VA_Numero de serie',
    'VA_Numero de lot',
    'VM_Geste valvulaire',
    'VM_Type de prothese',
    'VM_Fabricant',
    'VM_Modele',
    'VM_Taille (mm)',
    'VM_Numero de serie',
    'VM_Numero de lot',
    'VT_Geste valvulaire',
    'VT_Type de prothese',
    'VT_Fabricant',
    'VT_Modele',
    'VT_Taille (mm)',
    'VT_Numero de serie',
    'VT_Numero de lot',
    'VP_Geste valvulaire',
    'VP_Type de prothese',
    'VP_Fabricant',
    'VP_Modele',
    'VP_Taille (mm)',
    'VP_Numero de serie',
    'VP_Numero de lot',
    
    # Diagnostic et procedures
    'Diagnostic',
    'Indication',
    'Geste',
    'Plastie valve aortique',
    'Clampage aortique pour nouvelle plastie',
    'Localisation du geste chirurgical',
    'Stent',
    'Type de stent',
    'Nombre de tube vasculaire non valve',
    'Prothese valvulaire aortique',
    'Autres chirurgies',
    'Autres chirurgies non cardiaque : vasculaire',
    'Autres chirurgies non cardiaque : thoracique',
    'Drainage/ECMO/Assistance ventriculaire',
    
    # Transfusion et complications
    'Transfusion',
    'Type de PSL',
    'Complications',
    'Gravite globale',
    'Reintervention precoce',
    'Si oui : reintervention sous CEC',
    'Complication survenues',
    
    # Parametres post operatoires
    'Septum paradoxal',
    'Epanchemeent pericardique',
    'Epaisseur epanchement',
    'Localisation de l\'epanchement (circonferentiel/localise)',
    'Si epanchement localise',
    'Nature epanchement',
    'Compression des cavites',
    'Veine cave inf',
    
    # Évaluation post operatoire des valves
    'IA post op',
    'Fuite sur prothese',
    'Fuite sur plastie',
    'Surface indexee',
    'Index de permeabilite',
    'Surface orifice regurgitant',
    'Volume regurgitant',
    'IM residuelle',
    'Plastie, fuite residuelle',
    'Diametre. Anneau mitral',
    'IT residuelle',
    'Flux inverse des veines sus hepatiques',
    
    # Mesures anatomiques post operatoires
    'Flap intimal (OUI / NON)',
    'Calcification prothese Valv ao',
    'Epaississement feuillet valv ao',
    'Restriction mouvement valv ao',
    'Diametre sinus de valsalva',
    'Diametre ao tubulaire',
    'Diametre ao isthmique',
    'Diametre ao thoracique',
    
    # Suivi
    'Statut a la sortie',
    'Statut a J30',
    'Deces apres la sortie ou au dela de 30j'
]