info_fields = [
    # Informations démographiques et administratives
    'Date de naissance',
    'Sexe',
    'Poids',
    'Taille',
    'Date d\'admission',
    'Date d\'intervention',
    'Date de sortie',
    
    # Paramètres biologiques et état initial
    'Créat pré op',
    'Clairance de la créat',
    'Dialyse',
    
    # # Antécédents et comorbidités
     'Diabète',
     'Traitement diabète pré-op',
    # 'BPCO',
    # 'EI ttt par ATB',
    # 'EI sterilisée',
    # 'Atteinte neuro-musculo-squelettique',
    # 'Stenose carotidienne ou intervention',
    # 'AOMI',
    # 'Aorte intervention',
    # 'NYHA',
    # 'ATCD d\'autre chirurgie avec ouverture pericardiaque',
    # 'Nombre',
    # 'Type d\'intervention cardiaque ANT',
    # 'HTA',
    # 'Hypercholestérolémie',
    # 'Tabac',
    # 'FA',
    # 'Stimulateur cardiaque implanté',
    
    # # État cardiaque pré-opératoire
    # 'Angor classe IV',
    # 'IDM<90j',
    # 'TV ou FV<24h',
    # 'Choc cardiogénique/anurie/oligurie<24h',
    # 'Inotropes voie IV',
    # 'Ballon contre pulsion',
    # 'ECMO/ECLS',
    # 'Intubation pré op',
    # 'Massage cardiaque pré op',
    # 'FEVG',
    # 'PAPS',
    
    # # Caractéristiques de l'intervention
    # 'Degré d\'urgence',
    # 'Complexité de l\'intervention',
    # 'Chirurgie de l\'aorte',
    # 'Flap intimal',
    # 'Maladie des tissus elastiques',
    # 'CIV post infarctus',
    # 'NB branche coronaire sténosées',
    # 'SS TCCG',
    # 'ATCD ATL/Stent',
    
    # # Évaluation valvulaire
    # 'IA(0/1/2/3/4)',
    # 'RA',
    # 'Etiologie valve aortique',
    # 'IM(0/1/2/3/4)',
    # 'RM',
    # 'Etiologie valve mitrale',
    # 'IT',
    # 'Etiologie valve tricuspide',
    # 'IP',
    # 'RP',
    # 'Etiologie valve pulmonaire',
    
    # # Traitements préopératoires
    # 'AVK pre op',
    # 'NACO pre op',
    # 'AAG pre op',
    # 'double AAG',
    
    # # Contexte COVID
    # 'Sars Cov 2 proué par PCR',
    # 'COVID 19 symptomatique',
    # 'Patient reculé pour COVID 19',
    
    # # Paramètres échocardiographiques
    # 'FEVG',
    # 'DTD',
    # 'DTS',
    # 'SIV',
    # 'Paroi postérieure',
    # 'Chambre de chasse',
    # 'Cinétique paroi antérieure',
    # 'Cinétique paroi latérale',
    # 'Cinétique paroi inférieure',
    # 'Rupture pariétale ou CIV',
    # 'Epanchemeent péricardique',
    # 'VCI',
    # 'Epaississement péricarde',
    # 'Thrombus/Tumeur OD',
    # 'Thrombus/tumeur OG',
    # 'Aspect',
    
    # # Mesures valvulaires et hémodynamiques
    # 'IA',
    # 'Gradient max',
    # 'Gradient moyen',
    # 'Vmax',
    # 'Surface effective',
    # 'Surace indexéee',
    # 'iTV sous aortique',
    # 'ITV aortique',
    # 'Index de perméabillité',
    # 'SOR',
    # 'Volume regurgitant',
    # 'Temps 1/2 pression',
    # 'Reflux diastolique crosse (OUI/NON)',
    
    # # Évaluation mitrale
    # 'IM',
    # 'Prolapsus',
    # 'Rupture de cordage',
    # 'IM dystrophique (Barlow)',
    # 'Cordages épaissis/raccourcis',
    # 'Calcifications',
    # 'Diamètre anneau mitral',
    # 'OG dilatée',
    # 'Surface de l\'OG',
    # 'Volume de l\'OG',
    # 'Volume indexé de l\'OG',
    # 'SOR',
    # 'RM : surface effective',
    # 'RM : gradient moyen',
    
    # # Évaluation tricuspide et ventriculaire droite
    # 'IT',
    # 'SOR',
    # 'Diamètre anneau tricuspide',
    # 'TAPSE',
    # 'Strain longitudinal global',
    # 'S\'',
    # 'Rapport E/A',
    # 'Rapport E/E\'',
    # 'Fonction VD',
    # 'Flux inversé veines sus hépatiques',
    # 'V max',
    # 'PAPS',
    # 'Gradient moyen',
    # 'Dilatation OD',
    # 'Dilatation VD',
    # 'Dilatation VCI',
    
    # # Mesures anatomiques
    # 'Insuffisance pulmonaire',
    # 'Diamètre anneau pulmonaire',
    # 'Gradient maximal pulmonaire',
    # 'Gradient moyen pulmonaire',
    # 'Diamètre anneau aortique',
    # 'Sinus de valsalva',
    # 'JST',
    # 'Aorte tubulaire',
    # 'Diamètre tronc artère pulmonaire',
    
    # # Détails chirurgicaux
    # 'CEC',
    # 'Durée de clampage',
    # 'Durée CEC',
    # 'Intervention necessitant une protection cérébrale',
    # 'Type de protection cérébrale',
    # 'Geste video assisté',
    # 'Voie d\'abord',
    # 'Si voie d\'abord endovasculaire',
    # 'Si voie d\'abord transthoracique',
    # 'Si voie d\'abord périphérique',
    # 'Chirurgien 1',
    # 'Chirurgien 2',
    # 'Chirurgien en formation',
    # 'Chirurgien chirurgie structuelle',
    
    # # Informations sur la chirurgie
    # 'Type de chirurgie',
    # 'NB total de conduit artériel',
    # 'NB anastomoses coronaires avec conduit artériel',
    # 'NB total conduit veineux',
    # 'NB anastomoses coronaires avec conduit veineux',
    
    # # Informations sur les prothèses valvulaires
    # 'VA_Geste valvulaire',
    # 'VA_Type de prothèse',
    # 'VA_Fabricant',
    # 'VA_Modèle',
    # 'VA_Taille (mm)',
    # 'VA_Numéro de série',
    # 'VA_Numéro de lot',
    # 'VM_Geste valvulaire',
    # 'VM_Type de prothèse',
    # 'VM_Fabricant',
    # 'VM_Modèle',
    # 'VM_Taille (mm)',
    # 'VM_Numéro de série',
    # 'VM_Numéro de lot',
    # 'VT_Geste valvulaire',
    # 'VT_Type de prothèse',
    # 'VT_Fabricant',
    # 'VT_Modèle',
    # 'VT_Taille (mm)',
    # 'VT_Numéro de série',
    # 'VT_Numéro de lot',
    # 'VP_Geste valvulaire',
    # 'VP_Type de prothèse',
    # 'VP_Fabricant',
    # 'VP_Modèle',
    # 'VP_Taille (mm)',
    # 'VP_Numéro de série',
    # 'VP_Numéro de lot',
    
    # # Diagnostic et procédures
    # 'Diagnostic',
    # 'Indication',
    # 'Geste',
    # 'Plastie valve aortique',
    # 'Clampage aortique pour nouvelle plastie',
    # 'Localisation du geste chirurgical',
    # 'Stent',
    # 'Type de stent',
    # 'Nombre de tube vasculaire non valvé',
    # 'Prothèse valvulaire aortique',
    # 'Autres chirurgies',
    # 'Autres chirurgies non cardiaque : vasculaire',
    # 'Autres chirurgies non cardiaque : thoracique',
    # 'Drainage/ECMO/Assistance ventriculaire',
    
    # # Transfusion et complications
    # 'Transfusion',
    # 'Type de PSL',
    # 'Complications',
    # 'Gravité globale',
    # 'Réintervention précoce',
    # 'Si oui : réintervention sous CEC',
    # 'Complication survenues',
    
    # # Paramètres post-opératoires
    # 'FEVG',
    # 'DTD',
    # 'DTS',
    # 'SIV',
    # 'Paroi postérieure',
    # 'Septum paradoxal',
    # 'Epanchemeent péricardique',
    # 'Epaisseur épancchemeent',
    # 'Localisation de l\'épanchement (circonférentiel/localisé)',
    # 'Si épanchement localisé',
    # 'Nature épanchement',
    # 'Compression des cavités',
    # 'Veine cave InF',
    # 'Epaississement péricarde',
    
    # # Évaluation post-opératoire des valves
    # 'IA post op',
    # 'Fuite sur prothèse',
    # 'Fuite sur plastie',
    # 'Gradient max',
    # 'Gradient moyen',
    # 'V max',
    # 'Surface effective',
    # 'Surface indexée',
    # 'ITV sous aortique',
    # 'ITV aortique',
    # 'Index de peerméabilité',
    # 'Surface orifice régurgitant',
    # 'Volume régurgitant',
    # 'Temps 1/2 pression',
    # 'IM résiduelle',
    # 'Fuite sur prothèse',
    # 'Plastie, fuite résiduelle',
    # 'Dimaètre. Anneau mitral',
    # 'SOR',
    # 'Surface effective',
    # 'Gradient moyen',
    # 'IT résiduelle',
    # 'SOR',
    # 'TAPSE',
    # 'Fonction VD',
    # 'Flux inversé des veines sus-hépatiques',
    # 'Vmax',
    # 'PAPS',
    # 'Gradient moyen',
    # 'Dilatation OD',
    # 'Dilatation VD',
    # 'Dilatation VCI',
    # 'Gradient maximal pulmonaire',
    # 'Diamètre anneau pulmonaire',
    # 'Gradient moyen pulmonaire',
    
    # # Mesures anatomiques post-opératoires
    # 'Diamètre anneau aortique',
    # 'Sinus de valsalva',
    # 'JST',
    # 'Aorte tubulaire',
    # 'Flap intimal (OUI / NON)',
    # 'Calcification prothèse Vavlv ao',
    # 'Epaississement feuillet valv ao',
    # 'Restriction mouvement valv ao',
    # 'Diamètre anneau aortique',
    # 'Diamètre sinus de valsalva',
    # 'Diamètre ao tubulaire',
    # 'Diamètre ao isthmique',
    # 'Diamètre ao thoracique',
    # 'Diamètre anneau pulmonaire',
    # 'Diamètre tronc artère pulmonaire',
    
    # # Suivi
    # 'Statut à la sortie',
    # 'Statut à J30',
    # 'Décès après la sortie ou au-delà de 30j'
]